name: Aggregate Jobs
on:
  pull_request:

jobs:
  job1:
    uses: ./.github/workflows/job1.yml
  job2:
    uses: ./.github/workflows/job2.yml
  merge-guard:
    name: Wait for all checks to finish
    runs-on: ubuntu-latest
    needs: [ job1, job2 ]
    steps:
      - name: job summary
        run: exit 1